### ISSUE TITLE
[Bug] Can not begin to use issue

### ISSUE THREAD

**Issue by Kristinita** [arty-name/hunspell-merge#6]
## Кратко

Hunspell-merge не видит подключённых словарей.

## Цель

В Sublime Text 3, [использующем Hunspell](http://www.sublimetext.com/docs/3/spell_checking.html), сделать мультиязычный русско-английский словарь для спеллчекинга. У некоторых получилось, как расписано в [данном комментарии](https://github.com/SublimeTextIssues/Core/issues/1069#issuecomment-257945467), у меня нет. В поисках решения набрёл на hunspell-merge.

## Файлы

Файлы, которые хочу «мержить», лежащие в одной папке:

+ [EN.aff](https://github.com/titoBouzout/Dictionaries/blob/master/English%20(American).aff)
+ [EN.dic](https://github.com/titoBouzout/Dictionaries/blob/master/English%20(American).dic)
+ [EN.txt](https://github.com/titoBouzout/Dictionaries/blob/master/English%20(American).txt)
+ [RU.aff](https://github.com/titoBouzout/Dictionaries/blob/master/Russian.aff)
+ [RU.dic](https://github.com/titoBouzout/Dictionaries/blob/master/Russian.dic)
+ [RU.txt](https://github.com/titoBouzout/Dictionaries/blob/master/Russian.txt)

## Запуск bat

Клонировал на свой компьютер Ваш репозиторий, в папке `dist` запустил файл `HunspellMerge.bat` → нажимаю на кнопку с тремя точками под `Dictionaries source folder` → никаких файлов программа не видит.

![Не видно словарей](http://i.imgur.com/U7huvMT.png)

Пробовал копировать файлы для соединения в другую папку и выбирать эту другую папку, всё равно программа не видит эту папку.

Выскакивает консоль, содержимое:

```java
    wn Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

После того, как я закрываю программу, в папке ``dist`` появляется файл `hs_err_pid4932.log` со следующим содержимым.

<details>
    <summary>
        #
        # A fatal error has been detected by the Java Runtime Environment:
        #
        #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x75184d6d, pid=1076, tid=0x0000109c
        #
        # JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
        # Java VM: Java HotSpot(TM) Client VM (25.111-b14 mixed mode windows-x86 )
        # Problematic frame:
        # C  [IMAGEHLP.dll+0x4d6d]
        #
        # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
        #
        # If you would like to submit a bug report, please visit:
        #   http://bugreport.java.com/bugreport/crash.jsp
        # The crash happened outside the Java Virtual Machine in native code.
        # See problematic frame for where to report the bug.
        #

        ---------------  T H R E A D  ---------------

        Current thread (0x44171000):  JavaThread "AWT-Windows" daemon [_thread_in_native, id=4252, stack(0x44730000,0x44780000)]

        siginfo: ExceptionCode=0xc0000005, reading address 0x522b0014

        Registers:
        EAX=0x522b0014, EBX=0x522b0000, ECX=0x522b0000, EDX=0x00000000
        ESP=0x4477e870, EBP=0x4477e878, ESI=0x037d2410, EDI=0x7550db50
        EIP=0x75184d6d, EFLAGS=0x00010246

        Top of Stack: (sp=0x4477e870)
        0x4477e870:   522b0000 017d0000 4477e894 75184d28
        0x4477e880:   522b0000 00000001 00000001 4477e8cc
        0x4477e890:   00000000 0000082c 037d1388 522b0000
        0x4477e8a0:   00000001 00000001 4477e8cc 7550db50
        0x4477e8b0:   037d2410 0000082c 037d3094 037d12f9
        0x4477e8c0:   037d3094 7550db50 037d2410 522b0000
        0x4477e8d0:   4477ebf0 037d2060 004cc484 4477ebcc
        0x4477e8e0:   037d0000 0000082c 00000224 00000001 

        Instructions: (pc=0x75184d6d)
        0x75184d4d:   84 bb 2a 00 00 f6 c3 01 75 45 8a 45 0c 88 45 ff
        0x75184d5d:   53 e8 ad 00 00 00 85 c0 74 3e 8d 48 04 83 c0 18
        0x75184d6d:   0f b7 10 56 be 0b 01 00 00 66 3b d6 0f 85 9d 2a
        0x75184d7d:   00 00 8a 55 ff 50 51 ff 75 18 8b cb ff 75 14 ff 

        Register to memory mapping:

        EAX=0x522b0014 is an unknown value
        EBX=0x522b0000 is an unknown value
        ECX=0x522b0000 is an unknown value
        EDX=0x00000000 is an unknown value
        ESP=0x4477e870 is pointing into the stack for thread: 0x44171000
        EBP=0x4477e878 is pointing into the stack for thread: 0x44171000
        ESI=0x037d2410 is an unknown value
        EDI=0x7550db50 is an unknown value

        Stack: [0x44730000,0x44780000],  sp=0x4477e870,  free space=314k
        Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
        C  [IMAGEHLP.dll+0x4d6d]
        C  [IMAGEHLP.dll+0x4d28]
        C  [AmlMaple.dll+0x1388]

        Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
        j  sun.awt.windows.WToolkit.eventLoop()V+0
        j  sun.awt.windows.WToolkit.run()V+58
        j  java.lang.Thread.run()V+11
        v  ~StubRoutines::call_stub

        ---------------  P R O C E S S  ---------------

        Java Threads: ( => current thread )
          0x45437400 JavaThread "Thread-0" daemon [_thread_in_native, id=5064, stack(0x46740000,0x46790000)]
          0x0088c800 JavaThread "DestroyJavaVM" [_thread_blocked, id=3900, stack(0x007d0000,0x00820000)]
          0x4510dc00 JavaThread "AWT-EventQueue-0" [_thread_blocked, id=1964, stack(0x455d0000,0x45620000)]
        =>0x44171000 JavaThread "AWT-Windows" daemon [_thread_in_native, id=4252, stack(0x44730000,0x44780000)]
          0x44170800 JavaThread "AWT-Shutdown" [_thread_blocked, id=5536, stack(0x446e0000,0x44730000)]
          0x44170000 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=4012, stack(0x44690000,0x446e0000)]
          0x44167400 JavaThread "TimerQueue" daemon [_thread_blocked, id=5604, stack(0x44540000,0x44590000)]
          0x43ffb400 JavaThread "Service Thread" daemon [_thread_blocked, id=2128, stack(0x44360000,0x443b0000)]
          0x43ff6000 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=4180, stack(0x44310000,0x44360000)]
          0x43fff400 JavaThread "Attach Listener" daemon [_thread_blocked, id=1916, stack(0x442c0000,0x44310000)]
          0x43ffe800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=4768, stack(0x03770000,0x037c0000)]
          0x43fe9000 JavaThread "Finalizer" daemon [_thread_blocked, id=3912, stack(0x00ac0000,0x00b10000)]
          0x43fd3400 JavaThread "Reference Handler" daemon [_thread_blocked, id=4436, stack(0x00a70000,0x00ac0000)]

        Other Threads:
          0x009ec800 VMThread [stack: 0x00890000,0x008e0000] [id=1788]
          0x44030c00 WatcherThread [stack: 0x443b0000,0x44400000] [id=1444]

        VM state:not at safepoint (normal execution)

        VM Mutex/Monitor currently owned by a thread: None

        Heap:
         def new generation   total 4928K, used 2477K [0x03800000, 0x03d50000, 0x18d50000)
          eden space 4416K,  44% used [0x03800000, 0x039eb408, 0x03c50000)
          from space 512K, 100% used [0x03c50000, 0x03cd0000, 0x03cd0000)
          to   space 512K,   0% used [0x03cd0000, 0x03cd0000, 0x03d50000)
         tenured generation   total 10944K, used 3047K [0x18d50000, 0x19800000, 0x43800000)
           the space 10944K,  27% used [0x18d50000, 0x19049da0, 0x19049e00, 0x19800000)
         Metaspace       used 9305K, capacity 9543K, committed 9600K, reserved 9600K

        Card table byte_map: [0x43800000,0x43a10000] byte_map_base: 0x437e4000

        Polling page: 0x00820000

        CodeCache: size=32768Kb used=1384Kb max_used=1384Kb free=31384Kb
         bounds [0x01770000, 0x018d0000, 0x03770000]
         total_blobs=779 nmethods=539 adapters=171
         compilation: enabled

        Compilation events (10 events):
        Event: 45.451 Thread 0x43ff6000  537             java.util.HashMap::afterNodeAccess (1 bytes)
        Event: 45.451 Thread 0x43ff6000 nmethod 537 0x018c94c8 code [0x018c95c0, 0x018c9640]
        Event: 45.779 Thread 0x43ff6000  538             sun.awt.SunToolkit::getSystemEventQueueImplPP (13 bytes)
        Event: 45.779 Thread 0x43ff6000 nmethod 538 0x018c9688 code [0x018c9790, 0x018c983c]
        Event: 46.349 Thread 0x43ff6000  539             sun.awt.SunToolkit::getSystemEventQueueImpl (4 bytes)
        Event: 46.350 Thread 0x43ff6000 nmethod 539 0x018c9908 code [0x018c9a20, 0x018c9af8]
        Event: 46.350 Thread 0x43ff6000  540             sun.awt.SunToolkit::getSystemEventQueueImplPP (7 bytes)
        Event: 46.350 Thread 0x43ff6000 nmethod 540 0x018c9c08 code [0x018c9d20, 0x018c9de8]
        Event: 46.522 Thread 0x43ff6000  541             java.awt.EventDispatchThread$1::evaluate (2 bytes)
        Event: 46.522 Thread 0x43ff6000 nmethod 541 0x018c9ec8 code [0x018c9fc0, 0x018ca040]

        GC Heap History (4 events):
        Event: 0.972 GC heap before
        {Heap before GC invocations=0 (full 0):
         def new generation   total 4928K, used 4416K [0x03800000, 0x03d50000, 0x18d50000)
          eden space 4416K, 100% used [0x03800000, 0x03c50000, 0x03c50000)
          from space 512K,   0% used [0x03c50000, 0x03c50000, 0x03cd0000)
          to   space 512K,   0% used [0x03cd0000, 0x03cd0000, 0x03d50000)
         tenured generation   total 10944K, used 0K [0x18d50000, 0x19800000, 0x43800000)
           the space 10944K,   0% used [0x18d50000, 0x18d50000, 0x18d50200, 0x19800000)
         Metaspace       used 6954K, capacity 7150K, committed 7168K, reserved 7552K
        Event: 0.977 GC heap after
        Heap after GC invocations=1 (full 0):
         def new generation   total 4928K, used 512K [0x03800000, 0x03d50000, 0x18d50000)
          eden space 4416K,   0% used [0x03800000, 0x03800000, 0x03c50000)
          from space 512K, 100% used [0x03cd0000, 0x03d50000, 0x03d50000)
          to   space 512K,   0% used [0x03c50000, 0x03c50000, 0x03cd0000)
         tenured generation   total 10944K, used 1183K [0x18d50000, 0x19800000, 0x43800000)
           the space 10944K,  10% used [0x18d50000, 0x18e77ca8, 0x18e77e00, 0x19800000)
         Metaspace       used 6954K, capacity 7150K, committed 7168K, reserved 7552K
        }
        Event: 23.010 GC heap before
        {Heap before GC invocations=1 (full 0):
         def new generation   total 4928K, used 4928K [0x03800000, 0x03d50000, 0x18d50000)
          eden space 4416K, 100% used [0x03800000, 0x03c50000, 0x03c50000)
          from space 512K, 100% used [0x03cd0000, 0x03d50000, 0x03d50000)
          to   space 512K,   0% used [0x03c50000, 0x03c50000, 0x03cd0000)
         tenured generation   total 10944K, used 1183K [0x18d50000, 0x19800000, 0x43800000)
           the space 10944K,  10% used [0x18d50000, 0x18e77ca8, 0x18e77e00, 0x19800000)
         Metaspace       used 9102K, capacity 9311K, committed 9472K, reserved 9600K
        Event: 23.016 GC heap after
        Heap after GC invocations=2 (full 0):
         def new generation   total 4928K, used 512K [0x03800000, 0x03d50000, 0x18d50000)
          eden space 4416K,   0% used [0x03800000, 0x03800000, 0x03c50000)
          from space 512K, 100% used [0x03c50000, 0x03cd0000, 0x03cd0000)
          to   space 512K,   0% used [0x03cd0000, 0x03cd0000, 0x03d50000)
         tenured generation   total 10944K, used 3047K [0x18d50000, 0x19800000, 0x43800000)
           the space 10944K,  27% used [0x18d50000, 0x19049da0, 0x19049e00, 0x19800000)
         Metaspace       used 9102K, capacity 9311K, committed 9472K, reserved 9600K
        }

        Deoptimization events (0 events):
        No events

        Internal exceptions (10 events):
        Event: 0.027 Thread 0x0088c800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x03807138) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jni.cpp,
        Event: 0.371 Thread 0x0088c800 Exception <a 'java/security/PrivilegedActionException'> (0x03946000) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
        Event: 0.371 Thread 0x0088c800 Exception <a 'java/security/PrivilegedActionException'> (0x03946200) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
        Event: 0.371 Thread 0x0088c800 Exception <a 'java/security/PrivilegedActionException'> (0x03949a08) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
        Event: 0.371 Thread 0x0088c800 Exception <a 'java/security/PrivilegedActionException'> (0x03949c08) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
        Event: 0.423 Thread 0x0088c800 Exception <a 'java/io/FileNotFoundException'> (0x0394df98) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jni.cpp, line 709]
        Event: 0.462 Thread 0x0088c800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x03a09578) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
        Event: 0.463 Thread 0x0088c800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x03a157e0) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
        Event: 0.643 Thread 0x0088c800 Exception <a 'java/io/FileNotFoundException'> (0x03b0e500) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jni.cpp, line 709]
        Event: 45.030 Thread 0x4510dc00 Implicit null exception at 0x018be88f to 0x018c0103

        Events (10 events):
        Event: 46.888 Thread 0x45436c00 Thread added: 0x45436c00
        Event: 46.888 Thread 0x45437400 Thread added: 0x45437400
        Event: 46.889 Thread 0x45437800 Thread added: 0x45437800
        Event: 46.891 Thread 0x45436c00 Thread exited: 0x45436c00
        Event: 46.898 loading class sun/awt/shell/Win32ShellFolderManager2$ComInvoker$1$1
        Event: 46.898 loading class sun/awt/shell/Win32ShellFolderManager2$ComInvoker$1$1 done
        Event: 46.898 Thread 0x45437800 Thread exited: 0x45437800
        Event: 46.916 Executing VM operation: RevokeBias
        Event: 46.916 Executing VM operation: RevokeBias done
        Event: 46.916 Thread 0x441a4c00 Thread exited: 0x441a4c00

        Dynamic libraries:
        0x00b30000 - 0x00b63000     C:\ProgramData\Oracle\Java\javapath\java.exe
        0x77710000 - 0x77895000     C:\WINDOWS\SYSTEM32\ntdll.dll
        0x75830000 - 0x758c6000     C:\WINDOWS\System32\KERNEL32.DLL
        0x74c60000 - 0x74e06000     C:\WINDOWS\System32\KERNELBASE.dll
        0x72c50000 - 0x72ce2000     C:\WINDOWS\system32\apphelp.dll
        0x75060000 - 0x750d7000     C:\WINDOWS\System32\ADVAPI32.dll
        0x75420000 - 0x754de000     C:\WINDOWS\System32\msvcrt.dll
        0x775a0000 - 0x775e1000     C:\WINDOWS\System32\sechost.dll
        0x759d0000 - 0x75a93000     C:\WINDOWS\System32\RPCRT4.dll
        0x754e0000 - 0x75629000     C:\WINDOWS\System32\USER32.dll
        0x74360000 - 0x74379000     C:\WINDOWS\System32\win32u.dll
        0x74fd0000 - 0x74ffb000     C:\WINDOWS\System32\GDI32.dll
        0x74ac0000 - 0x74c1a000     C:\WINDOWS\System32\gdi32full.dll
        0x6caa0000 - 0x6ccaa000     C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.14393.447_none_89c64d28dafea4b9\COMCTL32.dll
        0x751a0000 - 0x753b1000     C:\WINDOWS\System32\combase.dll
        0x74e10000 - 0x74ef0000     C:\WINDOWS\System32\ucrtbase.dll
        0x74ef0000 - 0x74f4a000     C:\WINDOWS\System32\bcryptPrimitives.dll
        0x775f0000 - 0x77616000     C:\WINDOWS\System32\IMM32.DLL
        0x53620000 - 0x536df000     C:\Program Files\Java\jre1.8.0_111\bin\msvcr100.dll
        0x503a0000 - 0x5076d000     C:\Program Files\Java\jre1.8.0_111\bin\client\jvm.dll
        0x773f0000 - 0x773f6000     C:\WINDOWS\System32\PSAPI.DLL
        0x72ae0000 - 0x72b04000     C:\WINDOWS\SYSTEM32\WINMM.dll
        0x6ff00000 - 0x6ff08000     C:\WINDOWS\SYSTEM32\VERSION.dll
        0x67f50000 - 0x67f58000     C:\WINDOWS\SYSTEM32\WSOCK32.dll
        0x77370000 - 0x773d3000     C:\WINDOWS\System32\WS2_32.dll
        0x72a70000 - 0x72a93000     C:\WINDOWS\SYSTEM32\WINMMBASE.dll
        0x74c20000 - 0x74c56000     C:\WINDOWS\System32\cfgmgr32.dll
        0x6e3f0000 - 0x6e3fc000     C:\Program Files\Java\jre1.8.0_111\bin\verify.dll
        0x56490000 - 0x564b1000     C:\Program Files\Java\jre1.8.0_111\bin\java.dll
        0x64fe0000 - 0x64ff3000     C:\Program Files\Java\jre1.8.0_111\bin\zip.dll
        0x75b30000 - 0x76f09000     C:\WINDOWS\System32\SHELL32.dll
        0x74500000 - 0x74a6e000     C:\WINDOWS\System32\windows.storage.dll
        0x74260000 - 0x742a5000     C:\WINDOWS\System32\powrprof.dll
        0x77320000 - 0x77366000     C:\WINDOWS\System32\shlwapi.dll
        0x742b0000 - 0x742bd000     C:\WINDOWS\System32\kernel.appcore.dll
        0x75630000 - 0x756b8000     C:\WINDOWS\System32\shcore.dll
        0x74240000 - 0x7424f000     C:\WINDOWS\System32\profapi.dll
        0x50250000 - 0x50396000     C:\Program Files\Java\jre1.8.0_111\bin\awt.dll
        0x750e0000 - 0x75174000     C:\WINDOWS\System32\OLEAUT32.dll
        0x74f50000 - 0x74fcb000     C:\WINDOWS\System32\msvcp_win.dll
        0x72df0000 - 0x72e6a000     C:\WINDOWS\system32\uxtheme.dll
        0x77400000 - 0x77535000     C:\WINDOWS\System32\MSCTF.dll
        0x00b10000 - 0x00b22000     E:\RocketDock\RocketDock.dll
        0x037d0000 - 0x037d8000     E:\Aml Maple\AmlMaple.dll
        0x75180000 - 0x75199000     C:\WINDOWS\System32\IMAGEHLP.dll
        0x726d0000 - 0x726ef000     C:\WINDOWS\system32\dwmapi.dll
        0x758d0000 - 0x759ba000     C:\WINDOWS\System32\ole32.dll
        0x563f0000 - 0x56429000     C:\Program Files\Java\jre1.8.0_111\bin\fontmanager.dll
        0x556f0000 - 0x55706000     C:\Program Files\Java\jre1.8.0_111\bin\net.dll
        0x73b20000 - 0x73b70000     C:\WINDOWS\system32\mswsock.dll
        0x6e3e0000 - 0x6e3ef000     C:\Program Files\Java\jre1.8.0_111\bin\nio.dll
        0x555e0000 - 0x55612000     C:\Program Files\Java\jre1.8.0_111\bin\t2k.dll
        0x75aa0000 - 0x75b24000     C:\WINDOWS\System32\clbcatq.dll
        0x72000000 - 0x7216e000     C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
        0x65760000 - 0x657a4000     C:\WINDOWS\system32\dataexchange.dll
        0x72920000 - 0x72a33000     C:\WINDOWS\system32\dcomp.dll
        0x71be0000 - 0x71e0f000     C:\WINDOWS\system32\d3d11.dll
        0x73500000 - 0x73584000     C:\WINDOWS\system32\dxgi.dll
        0x73040000 - 0x73131000     C:\WINDOWS\system32\twinapi.appcore.dll
        0x741a0000 - 0x741bd000     C:\WINDOWS\system32\bcrypt.dll
        0x44f30000 - 0x44f3b000     E:\WonderfulIcon\wondppet.dll
        0x6bd80000 - 0x6be14000     C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.14393.447_none_5507ded2cb4f7f4c\comctl32.dll
        0x62a90000 - 0x62bb4000     C:\WINDOWS\system32\NetworkExplorer.dll
        0x724f0000 - 0x7263f000     C:\WINDOWS\system32\PROPSYS.dll
        0x6e710000 - 0x6e895000     C:\Windows\System32\ActXPrxy.dll
        0x68300000 - 0x68316000     C:\WINDOWS\SYSTEM32\MPR.dll
        0x53700000 - 0x53712000     C:\WINDOWS\System32\ntlanman.dll
        0x69de0000 - 0x69de9000     C:\WINDOWS\System32\drprov.dll
        0x74150000 - 0x74193000     C:\WINDOWS\System32\WINSTA.dll
        0x53600000 - 0x5361a000     C:\WINDOWS\System32\davclnt.dll
        0x67890000 - 0x6789b000     C:\WINDOWS\System32\DAVHLPR.dll
        0x6fee0000 - 0x6fef0000     C:\WINDOWS\System32\wkscli.dll
        0x67840000 - 0x6784f000     C:\WINDOWS\SYSTEM32\cscapi.dll
        0x739c0000 - 0x739cb000     C:\WINDOWS\System32\netutils.dll
        0x53590000 - 0x535d2000     C:\Windows\System32\dlnashext.dll
        0x56430000 - 0x56488000     C:\Windows\System32\PlayToDevice.dll
        0x53220000 - 0x5323b000     C:\Windows\System32\DevDispItemProvider.dll
        0x6eda0000 - 0x6edf8000     C:\WINDOWS\System32\MMDevApi.dll
        0x73210000 - 0x73232000     C:\WINDOWS\System32\DEVOBJ.dll
        0x705b0000 - 0x70633000     C:\Windows\System32\PortableDeviceApi.dll
        0x76f10000 - 0x7731b000     C:\WINDOWS\System32\SETUPAPI.dll
        0x74a70000 - 0x74ab4000     C:\WINDOWS\System32\WINTRUST.dll
        0x74250000 - 0x7425e000     C:\WINDOWS\System32\MSASN1.dll
        0x74380000 - 0x744fd000     C:\WINDOWS\System32\CRYPT32.dll
        0x71670000 - 0x71782000     C:\WINDOWS\SYSTEM32\MFPlat.DLL
        0x71610000 - 0x7163a000     C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
        0x65500000 - 0x65520000     C:\Windows\System32\EhStorAPI.dll
        0x724e0000 - 0x724ef000     C:\Windows\System32\WTSAPI32.dll
        0x65830000 - 0x6583d000     C:\WINDOWS\SYSTEM32\LINKINFO.dll
        0x634f0000 - 0x6359f000     C:\WINDOWS\system32\Windows.Storage.Search.dll
        0x69e20000 - 0x69f65000     C:\WINDOWS\SYSTEM32\dbghelp.dll

        VM Arguments:
        jvm_args: -Xmx1024m 
        java_command: hunspell.merge.HunspellMerge
        java_class_path (initial): HunspellMerge.jar
        Launcher Type: SUN_STANDARD

        Environment Variables:
        JAVA_HOME=C:\Program Files\Java\jdk1.8.0_112
        CLASSPATH=.
        PATH=C:\Program Files\ImageMagick-7.0.3-Q16;E:\Python35-32\Scripts\;E:\Python35-32\;C:\Program Files\ImageMagick-7.0.2-Q16;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Skype\Phone\;C:\Program Files\Java\jre7\bin;E:\Chocolatey\bin;C:\Program Files\OpenVPN\bin;C:\Program Files\Git LFS;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\Program Files\nodejs\;E:\Scala\bin;C:\Program Files\Java\jdk1.8.0_112\bin;C:\Program Files\Git\cmd;E:\Rust stable GNU 1.12\bin;C:\Program Files\GNU\GnuPG\pub;E:\OpenVPNInstall\bin;C:\Program Files\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\ImageMagick-7.0.3-Q16;E:\Python35-32\Scripts\;E:\Python35-32\;C:\Program Files\ImageMagick-7.0.2-Q16;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Skype\Phone\;C:\Program Files\Java\jre7\bin;E:\Chocolatey\bin;C:\Program Files\OpenVPN\bin;E:\OpenVPNInstall\bin;C:\Program Files\Git LFS;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\Program Files\nodejs\;E:\Scala\bin;C:\Program Files\Java\jdk1.8.0_112\bin;C:\Program Files\Git\cmd;E:\Rust stable GNU 1.12\bin;E:\Ruby23\bin;C:\Users\Кот\AppData\Local\Microsoft\WindowsApps;C:\Users\Кот\AppData\Local\GitHubCLI\bin;C:\Program Files\wkhtmltopdf\bin;E:\Sublime Text 3;E:\Chocolatey\tools\php;E:\Chocolatey\lib\python3\tools\Scripts;C:\Users\Кот\AppData\Local\Pandoc\;C:\Users\Кот\AppData\Roaming\npm;E:\Zeal;C:\PROGRA~1\Oracle\VirtualBox;E:\Chocolatey\lib\msys2;E:\Chocolatey\tools\msys32;E:\msys32\mingw32\bin;E:\Chocolatey\lib\sox.portable\lib;E:\Chocolatey\tools\cmder;C:\Program Files\ConEmu
        USERNAME=SashaChernykh
        OS=Windows_NT
        PROCESSOR_IDENTIFIER=x86 Family 6 Model 60 Stepping 3, GenuineIntel

        ---------------  S Y S T E M  ---------------

        OS: Windows 10.0 Build 14393 (10.0.14393.0)

        CPU:total 4 (2 cores per cpu, 2 threads per core) family 6 model 60 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2

        Memory: 4k page, physical 3578132k(1431528k free), swap 5347604k(2364512k free)

        vm_info: Java HotSpot(TM) Client VM (25.111-b14) for windows-x86 JRE (1.8.0_111-b14), built on Sep 22 2016 18:54:33 by "java_re" with MS VC++ 10.0 (VS2010)

        time: Mon Nov 14 10:08:55 2016
        elapsed time: 47 seconds (0d 0h 0m 47s)

    </summary>
</details>

## Запуск jnlp

Кликаю дважды левой кнопкой мыши по файлу `HunspellMerge.jnlp` → всплывает окно:

> Unable to launch the application

![Unable to launch the application](http://i.imgur.com/V1nnEHZ.png)

`Details` → под вкладкой `Exception` вижу:

```java
    com.sun.deploy.net.FailedDownloadException: Unable to load resource: http://hunspell-merge.googlecode.com/files/HunspellMerge.jnlp
        at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
        at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
        at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
        at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
        at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
        at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
        at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
        at com.sun.javaws.Launcher.launch(Unknown Source)
        at com.sun.javaws.Main.launchApp(Unknown Source)
        at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
        at com.sun.javaws.Main.access$000(Unknown Source)
        at com.sun.javaws.Main$1.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Под вкладкой `Wrapped Exception`:

```java
com.sun.deploy.net.FailedDownloadException: Unable to load resource: http://hunspell-merge.googlecode.com/files/HunspellMerge.jnlp
    at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
    at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
    at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
    at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
    at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
    at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
    at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
    at com.sun.javaws.Launcher.launch(Unknown Source)
    at com.sun.javaws.Main.launchApp(Unknown Source)
    at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
    at com.sun.javaws.Main.access$000(Unknown Source)
    at com.sun.javaws.Main$1.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

## Программно-аппаратное окружение

См. содержимое файла `hs_err_pid4932.log`.

Спасибо.

**Comment by arty-name** [comment]
У меня почему-то были отключены оповещения об активности в этом репозитории, поэтому сегодня я в первый раз увидел ваш комментарий. К сожалению, пользы от этого немного: я не java-программист, и репозиторием этим владею исключительно потому, что спас его с Google Code перед отключением оного. Могу только предположить, что другая ОС или другая версия JRE могут помочь.
